# deployment/docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: instabids-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: supabase/postgres:15.1.0
    container_name: instabids-postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./deployment/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=yoursecurepassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: instabids-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=http://db:5432 # Placeholder, use real URL in prod
      - SUPABASE_SERVICE_ROLE_KEY=your_supabase_key # Placeholder
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  # CORE AGENT WORKERS - These were missing and are now FIXED!
  homeowner-intake-agent:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: instabids-homeowner-intake-agent
    command: python -c "
      import asyncio
      from agents.homeowner_intake.intake_agent import HomeownerIntakeAgent
      
      async def main():
          agent = HomeownerIntakeAgent()
          await agent.start_processing()
      
      asyncio.run(main())
    "
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=https://tqthesdjiewlcxpvqmjl.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AGENT_TYPE=homeowner_intake
      - AGENT_ID=homeowner-intake-001
    restart: unless-stopped
    depends_on:
      - redis
      - db
    networks:
      - agent-swarm

  project-scope-agent:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: instabids-project-scope-agent
    command: python -c "
      import asyncio
      from agents.project_scope.scope_agent import ProjectScopeAgent
      
      async def main():
          agent = ProjectScopeAgent()
          await agent.start_processing()
      
      asyncio.run(main())
    "
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=https://tqthesdjiewlcxpvqmjl.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AGENT_TYPE=project_scope
      - AGENT_ID=project-scope-001
    restart: unless-stopped
    depends_on:
      - redis
      - db
    networks:
      - agent-swarm

  communication-filter-agent:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: instabids-communication-filter-agent
    command: python -c "
      import asyncio
      from agents.communication_filter.filter_agent import CommunicationFilterAgent
      
      async def main():
          agent = CommunicationFilterAgent()
          await agent.start_processing()
      
      asyncio.run(main())
    "
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=https://tqthesdjiewlcxpvqmjl.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - AGENT_TYPE=communication_filter
      - AGENT_ID=communication-filter-001
    restart: unless-stopped
    depends_on:
      - redis
      - db
    networks:
      - agent-swarm

  payment-gate-agent:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: instabids-payment-gate-agent
    command: python -c "
      import asyncio
      from agents.payment_gate.payment_agent import PaymentGateAgent
      
      async def main():
          agent = PaymentGateAgent()
          await agent.start_processing()
      
      asyncio.run(main())
    "
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=https://tqthesdjiewlcxpvqmjl.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - AGENT_TYPE=payment_gate
      - AGENT_ID=payment-gate-001
    restart: unless-stopped
    depends_on:
      - redis
      - db
    networks:
      - agent-swarm

  ui-generator-agent:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: instabids-ui-generator-agent
    command: python -c "
      import asyncio
      from agents.ui_generator.ui_agent import UIGeneratorAgent
      
      async def main():
          agent = UIGeneratorAgent()
          await agent.start_processing()
      
      asyncio.run(main())
    "
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=https://tqthesdjiewlcxpvqmjl.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - AGENT_TYPE=ui_generator
      - AGENT_ID=ui-generator-001
    restart: unless-stopped
    depends_on:
      - redis
      - db
    networks:
      - agent-swarm

  # LiveKit Media Server for real-time video/audio
  livekit:
    image: livekit/livekit-server:latest
    container_name: instabids-livekit-server
    restart: unless-stopped
    ports:
      - "7880:7880"    # Server API
      - "7881:7881"    # WebRTC
      - "7882:7882/udp" # TURN/UDP
    environment:
      LIVEKIT_KEYS: "devkey: secret"
      LIVEKIT_PORT: 7880
      LIVEKIT_RTC_PORT: 7881
    networks:
      - agent-swarm
    volumes:
      - ./config/livekit.yaml:/etc/livekit.yaml

  # Media Processor Agent for video/audio processing
  media-processor-agent:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: instabids-media-processor-agent
    restart: unless-stopped
    environment:
      REDIS_URL: redis://redis:6379
      LIVEKIT_URL: "http://livekit:7880"
      LIVEKIT_API_KEY: "devkey"
      LIVEKIT_API_SECRET: "secret"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AGENT_TYPE: media_processor
      AGENT_ID: media-processor-001
    volumes:
      - agent-logs:/app/logs
    networks:
      - agent-swarm
    depends_on:
      - redis
      - livekit

networks:
  agent-swarm:
    driver: bridge

volumes:
  redis_data:
  db_data:
  agent-logs:
